
services:
#================================================================================
# MYSQL
#================================================================================
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
